export const new_school_data =
[{
  "_id": {
    "$oid": "66e85396072523935641b7e1"
  },
  "UDISE_CODE": "29  20  01  23  915",
  "School_Name": "JNANA JYOTHI CONVENT",
  "State": "Karnataka",
  "School_Category": "2",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,8)",
  "Year_of_Establishment": "2005",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "10",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "5",
  "Total_Washrooms": "(1,1)",
  "CWSN": false,
  "Total_Students": "32",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66e853ce072523935641b7e2"
  },
  "UDISE_CODE": "29  20  01  23  908",
  "School_Name": "SKANDA STEP P.U.COLLEGE",
  "State": "Karnataka",
  "School_Category": "11",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(11,12)",
  "Year_of_Establishment": "2012",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "6",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "0",
  "Total_Washrooms": "(2,2)",
  "CWSN": true,
  "Total_Students": "96",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66e853d4072523935641b7e3"
  },
  "UDISE_CODE": "29  20  01  23  910",
  "School_Name": "VISHWA BHARATHI HIGH SCHOOL",
  "State": "Karnataka",
  "School_Category": "6",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,10)",
  "Year_of_Establishment": "1986",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "39",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "12",
  "Total_Washrooms": "(8,8)",
  "CWSN": true,
  "Total_Students": "644",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66e853ec072523935641b7e4"
  },
  "UDISE_CODE": "29  20  01  23  917",
  "School_Name": "SKANDA'S VIDYALAYA(R)",
  "State": "Karnataka",
  "School_Category": "3",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,12)",
  "Year_of_Establishment": "2006",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "32",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "4",
  "Total_Washrooms": "(1,6)",
  "CWSN": false,
  "Total_Students": "369",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66e853f4072523935641b7e5"
  },
  "UDISE_CODE": "29  20  01  23  920",
  "School_Name": "GLPS  BHUVANESHWARI NAGARA",
  "State": "Karnataka",
  "School_Category": "1",
  "School_Management": "1",
  "School_Type": "3",
  "Grade_Configuration": "(1,5)",
  "Year_of_Establishment": "1997",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "4",
  "Library_Available": true,
  "Separate_Room_for_HM": false,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "1",
  "Total_Washrooms": "(3,3)",
  "CWSN": true,
  "Total_Students": "95",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66e853fb072523935641b7e6"
  },
  "UDISE_CODE": "29  20  01  23  924",
  "School_Name": "ROTARY BANGALORE VIDYALAYA",
  "State": "Karnataka",
  "School_Category": "6",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,10)",
  "Year_of_Establishment": "1993",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "15",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "13",
  "Total_Washrooms": "(6,6)",
  "CWSN": true,
  "Total_Students": "224",
  "Result": "Standard"
},
{
  "_id": {
    "$oid": "66eec6decf0249423d55362a"
  },
  "UDISE_CODE": "21  17  13  03  551",
  "School_Name": "RUCHIKA HIGH SCHOOL, UNIT 6",
  "State": "Odisha",
  "School_Category": "6",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,10)",
  "Year_of_Establishment": "1985",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "20",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "23",
  "Total_Washrooms": "(101,0)",
  "CWSN": false,
  "Total_Students": "349",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66eecb69cf0249423d55363a"
  },
  "UDISE_CODE": "21  17  13  02  776",
  "School_Name": "M.B.S PUBLIC SCHOOL UNIT-9",
  "State": "Odisha",
  "School_Category": "3",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,12)",
  "Year_of_Establishment": "2004",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "47",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "63",
  "Total_Washrooms": "(9,9)",
  "CWSN": false,
  "Total_Students": "1887",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66eef28bcf0249423d553650"
  },
  "UDISE_CODE": "29  20  01  23  926",
  "School_Name": "GHS   DODDAGOLLARA HATTI",
  "State": "Karnataka",
  "School_Category": "8",
  "School_Management": "1",
  "School_Type": "3",
  "Grade_Configuration": "(9,10)",
  "Year_of_Establishment": "1991",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "6",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "9",
  "Total_Washrooms": "(2,3)",
  "CWSN": false,
  "Total_Students": "221",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66eef2d2cf0249423d553653"
  },
  "UDISE_CODE": "18  27  11  01  928",
  "School_Name": "DISPUR ADARSHA LPS",
  "State": "Assam",
  "School_Category": "1",
  "School_Management": "1",
  "School_Type": "3",
  "Grade_Configuration": "(0,5)",
  "Year_of_Establishment": "1957",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "5",
  "Library_Available": true,
  "Separate_Room_for_HM": false,
  "Drinking_Water_Available": true,
  "Playground_Available": false,
  "Electricity_Availability": true,
  "Total_Teachers": "3",
  "Total_Washrooms": "(1,2)",
  "CWSN": false,
  "Total_Students": "12",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "66f032b547ff165f93f4e5dc"
  },
  "UDISE_CODE": "29  20  01  23  928",
  "School_Name": "NEW HORIZON ENG SCH",
  "State": "Karnataka",
  "School_Category": "3",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,12)",
  "Year_of_Establishment": "1998",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "13",
  "Library_Available": true,
  "Separate_Room_for_HM": false,
  "Drinking_Water_Available": true,
  "Playground_Available": false,
  "Electricity_Availability": true,
  "Total_Teachers": "21",
  "Total_Washrooms": "(4,4)",
  "CWSN": false,
  "Total_Students": "224",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "675717c95b7ee5b64987cef9"
  },
  "UDISE_CODE": "29  20  01  23  931",
  "School_Name": "GHPS  DODDABASTI",
  "State": "Karnataka",
  "School_Category": "2",
  "School_Management": "1",
  "School_Type": "3",
  "Grade_Configuration": "(1,8)",
  "Year_of_Establishment": "1989",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "6",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "5",
  "Total_Washrooms": "(2,2)",
  "CWSN": true,
  "Total_Students": "180",
  "Result": "Standard"
},
{
  "_id": {
    "$oid": "6757dff85b7ee5b64987cf2c"
  },
  "UDISE_CODE": "33  02  10  00  914",
  "School_Name": "P.S HIGHER SECONDARY SCHOOL",
  "State": "Tamilnadu",
  "School_Category": "5",
  "School_Management": "4",
  "School_Type": "1",
  "Grade_Configuration": "(6,12)",
  "Year_of_Establishment": "1905",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "29",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "36",
  "Total_Washrooms": "(32,0)",
  "CWSN": true,
  "Total_Students": "912",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "67596fa4111eda7458cb7b6f"
  },
  "UDISE_CODE": "21  17  13  03  503",
  "School_Name": "GOVT. HIGH SCHOOL,  UNIT-6",
  "State": "Odisha",
  "School_Category": "6",
  "School_Management": "1",
  "School_Type": "3",
  "Grade_Configuration": "(1,10)",
  "Year_of_Establishment": "1964",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "22",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "24",
  "Total_Washrooms": "(4,4)",
  "CWSN": false,
  "Total_Students": "983",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "67597dab111eda7458cb7b77"
  },
  "UDISE_CODE": "20  14  01  14  012",
  "School_Name": "HOLY CROSS SCHOOL",
  "State": "Jharkhand",
  "School_Category": "6",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,10)",
  "Year_of_Establishment": "2010",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "33",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "44",
  "Total_Washrooms": "(2,1)",
  "CWSN": false,
  "Total_Students": "1262",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "67599049425aaac55579cade"
  },
  "UDISE_CODE": "06  01  01  00  116",
  "School_Name": "SAARTHAK GIMSSSS SECTOR-12A PKL",
  "State": "Haryana",
  "School_Category": "5",
  "School_Management": "1",
  "School_Type": "3",
  "Grade_Configuration": "(6,12)",
  "Year_of_Establishment": "2003",
  "Boundary_Wall": true,
  "Total_Class_Rooms": "30",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "49",
  "Total_Washrooms": "(91,4)",
  "CWSN": false,
  "Total_Students": "1486",
  "Result": "Standard"
},
{
  "_id": {
    "$oid": "67599610111eda7458cb7b81"
  },
  "UDISE_CODE": "33  02  10  00  918",
  "School_Name": "PS SENIOR SECONDARY SCHOOL",
  "State": "Tamilnadu",
  "School_Category": "3",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,12)",
  "Year_of_Establishment": "1976",
  "Boundary_Wall": false,
  "Total_Class_Rooms": "72",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "140",
  "Total_Washrooms": "(514,5)",
  "CWSN": false,
  "Total_Students": "2746",
  "Result": "Standard"
},
{
  "_id": {
    "$oid": "6759976a425aaac55579cae6"
  },
  "UDISE_CODE": "18  27  11  02  558",
  "School_Name": "LITTLE TOTS ENGLISH SCHOOL",
  "State": "Assam",
  "School_Category": "6",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,10)",
  "Year_of_Establishment": "1995",
  "Boundary_Wall": true,
  "Total_Class_Rooms": "13",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "21",
  "Total_Washrooms": "(2,2)",
  "CWSN": false,
  "Total_Students": "411",
  "Result": "Standard"
},
{
  "_id": {
    "$oid": "6759978e425aaac55579cae7"
  },
  "UDISE_CODE": "36  22  06  90  153",
  "School_Name": "AIDED ANDHRA VIDY PS AIDED,KATTELMANDI",
  "State": "Telangana",
  "School_Category": "1",
  "School_Management": "4",
  "School_Type": "3",
  "Grade_Configuration": "(1,5)",
  "Year_of_Establishment": "1944",
  "Boundary_Wall": true,
  "Total_Class_Rooms": "5",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "3",
  "Total_Washrooms": "(6,4)",
  "CWSN": false,
  "Total_Students": "88",
  "Result": "Standard"
},
{
  "_id": {
    "$oid": "6759979a425aaac55579cae8"
  },
  "UDISE_CODE": "08  12  26  05  205",
  "School_Name": "SAINT PAUL'S SCHOOL SR.SEC.",
  "State": "Rajasthan",
  "School_Category": "3",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,12)",
  "Year_of_Establishment": "1995",
  "Boundary_Wall": true,
  "Total_Class_Rooms": "20",
  "Library_Available": true,
  "Separate_Room_for_HM": false,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "19",
  "Total_Washrooms": "(4,4)",
  "CWSN": false,
  "Total_Students": "298",
  "Result": "ODD"
},
{
  "_id": {
    "$oid": "67599a39425aaac55579caee"
  },
  "UDISE_CODE": "29  20  01  23  947",
  "School_Name": "JANANI VIDYA MANDIRA",
  "State": "Karnataka",
  "School_Category": "6",
  "School_Management": "5",
  "School_Type": "3",
  "Grade_Configuration": "(1,10)",
  "Year_of_Establishment": "2012",
  "Boundary_Wall": true,
  "Total_Class_Rooms": "19",
  "Library_Available": true,
  "Separate_Room_for_HM": true,
  "Drinking_Water_Available": true,
  "Playground_Available": true,
  "Electricity_Availability": true,
  "Total_Teachers": "26",
  "Total_Washrooms": "(141,4)",
  "CWSN": false,
  "Total_Students": "511",
  "Result": "Standard"
}]